#!/bin/sh

feh --bg-fill ~/Pictures/Wallpapers/911.jpg &
picom &
xrandr --output HDMI-1-0 --auto --above eDP-1 --rotate inverted &
slstatus &
safeeyes &
notion-desktop &
thunderbird &
newsflash &
foliate &
dwm # MUST BE AT END 

